---
title: "The Great Quiz Book"
author: "Abdullah Al Mahmud"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    extra_dependencies: ["enumitem"]
  word_document:
    toc: true
    toc_depth: '3'
documentclass: report
geometry: margin=2cm
---

\newpage

\begingroup
\fontfamily{ppl}\fontsize{12}{16}\selectfont

# Math Problems

## Velocity 

### NY and LA Train 

A train leaves New York at 8:00 AM traveling west at 60 mph. Another train leaves Los Angeles at 6:00 AM traveling east at 70 mph on the same track. If the distance between New York and Los Angeles is 2,800 miles, at what time will the two trains meet?[^NYLA]

[^NYLA]: The two trains will meet at 4:28 AM the next day. 
    
    **Distance** = $2800 - 70 \times 2 hours = 2660$ miles. $Time = \frac{2600}{60+70}$. 
    
    **Alternate method**: If they meet after `t` hours, $x = 60t$ and $2800-x = 70(t+2)$. Solve for t. 
    
    ** Another method**: $\frac{x}{60} = \frac{2600-x}{70}$
    
### Fly flyhing between trains

Two trains are on the same track a distance 100 km apart heading towards one another, each at a speed of 50 km/h. A fly starting out at the front of one train, flies towards the other at a speed of 75 km/h. Upon reaching the other train, the fly turns around and continues towards the first train. How many kilometers does the fly travel before getting squashed in the collision of the two trains? [^fly]

[^fly]: The fly flies for as many hours as the trains take to meet. As the trains meet after 1 hour, in the middle, the fly flies 75 km in 1 hour.

## Number Theory

### Divisible by 11 and difference

Let us call all numbers divisible by 11 'Beautiful Numbers'. What is the difference between the largest and smallest five-digit 'Beautiful Number'? [^divdiff]

[^divdiff]: 

    Largest: 99990, 
Smallest: 11110, 
Difference: 88880


# Statistics

## Basic Questions

### Average with origin, scale changed

The average of 10 numbers is 49. If each of the numbers is divided by 7 and the quotient is then added by 5, what is the changed average number?[^avgorsc]

[^avgorsc]: 

    $\frac{49}{7}+5 = 12$

# Puzzles

## Logic 

A shepherd has to cross a river with a sheep, a wolf and a cabbage. Only two can go on the boat, for example, the shepherd and the sheep. How can they cross the river without the wolf eating the sheep and or the sheep eating the cabbage? [^shwocb]

[^shwocb]: In the following order --

    i. Bring sheep
ii. Bring back nothing
iii. Bring wolf
iv. Bring back sheep
v. Bring cabbage
vi. Bring back nothing
vii. Bring wolf

### Lock Puzzle 01

There is a combination lock lock with three digits.[^L1] The clues are the following:

| Digits | No. of Correct Digits | Position |
|:---:|:---:|:---:|
| 964 | 2 | Wrong |
| 286 | 1 | Wrong |
| 147 | 1 | Wrong |
| 189 | 1 | Correct |
| 523 | 0 | NA |

[^L1]: 679

    \begin{enumerate}[label=(\alph*)]
\item 523 are removed by clue no. 5
\item 1 is removed by clue 3 \& 4 (can't be in right and wrong position simultaneously)
\item 8 is removed by clue 2 \& 4 (can't be in right and wrong position simultaneously)
\item 6 is correct digit by clue 2 (since 2 \& are wrong)
\item Position of 6 is 1st (by clue 1 \& 2, both wrong position)
\item 9 is the 3rd digit in solution by clue 4 (since 1 \& 8 are incorrect)
\item 4 is removed by clue 1 (since two correct digits are 9 \& 6)
\item The 2nd digit in solution is 7 (by clue 3 and since no other digit exists)
\end{enumerate}

### Shepherd dilemma

A shepherd has to cross a river with a sheep, a wolf and a cabbage. Only two can go on the boat, for example, the shepherd and the sheep. How can they cross the river without the wolf eating the sheep and or the sheep eating the cabbage?[^shp]

[^shp]: 

i. Bring sheep
ii. Bring back nothing
iii. Bring wolf
iv. Bring back sheep
v. Bring cabbage
vi. Bring back nothing
vii. Bring wolf

\endgroup